# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1019, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.infoLabel = QtWidgets.QLabel(Dialog)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 2, 1, 1, 1)
        self.currentPortLabel = QtWidgets.QLabel(Dialog)
        self.currentPortLabel.setObjectName("currentPortLabel")
        self.gridLayout.addWidget(self.currentPortLabel, 2, 0, 1, 1)
        self.currentConfigLabel = QtWidgets.QLabel(Dialog)
        self.currentConfigLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentConfigLabel.setObjectName("currentConfigLabel")
        self.gridLayout.addWidget(self.currentConfigLabel, 2, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.settings_tab)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.portsList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portsList.sizePolicy().hasHeightForWidth())
        self.portsList.setSizePolicy(sizePolicy)
        self.portsList.setMinimumSize(QtCore.QSize(70, 0))
        self.portsList.setCurrentText("")
        self.portsList.setMinimumContentsLength(1)
        self.portsList.setObjectName("portsList")
        self.portsList.addItem("")
        self.portsList.setItemText(0, "")
        self.gridLayout_2.addWidget(self.portsList, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settings_tab)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 2)
        self.refreshPortsButton = QtWidgets.QPushButton(self.settings_tab)
        self.refreshPortsButton.setObjectName("refreshPortsButton")
        self.gridLayout_2.addWidget(self.refreshPortsButton, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.dataWidthList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataWidthList.sizePolicy().hasHeightForWidth())
        self.dataWidthList.setSizePolicy(sizePolicy)
        self.dataWidthList.setMinimumSize(QtCore.QSize(70, 0))
        self.dataWidthList.setObjectName("dataWidthList")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.gridLayout_2.addWidget(self.dataWidthList, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settings_tab)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 2, 1, 1)
        self.parityList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parityList.sizePolicy().hasHeightForWidth())
        self.parityList.setSizePolicy(sizePolicy)
        self.parityList.setMinimumSize(QtCore.QSize(70, 0))
        self.parityList.setObjectName("parityList")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.gridLayout_2.addWidget(self.parityList, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings_tab)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 2, 1, 1)
        self.stopBitsList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBitsList.sizePolicy().hasHeightForWidth())
        self.stopBitsList.setSizePolicy(sizePolicy)
        self.stopBitsList.setMinimumSize(QtCore.QSize(70, 0))
        self.stopBitsList.setObjectName("stopBitsList")
        self.stopBitsList.addItem("")
        self.stopBitsList.addItem("")
        self.stopBitsList.addItem("")
        self.gridLayout_2.addWidget(self.stopBitsList, 5, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 5, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.settings_tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 2, 1, 1)
        self.baudrateList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrateList.sizePolicy().hasHeightForWidth())
        self.baudrateList.setSizePolicy(sizePolicy)
        self.baudrateList.setMinimumSize(QtCore.QSize(70, 0))
        self.baudrateList.setObjectName("baudrateList")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.gridLayout_2.addWidget(self.baudrateList, 6, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 6, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settings_tab)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 2, 1, 1)
        self.flowControlList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowControlList.sizePolicy().hasHeightForWidth())
        self.flowControlList.setSizePolicy(sizePolicy)
        self.flowControlList.setMinimumSize(QtCore.QSize(70, 0))
        self.flowControlList.setObjectName("flowControlList")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.gridLayout_2.addWidget(self.flowControlList, 9, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 9, 4, 1, 1)
        self.openCloseButton = QtWidgets.QPushButton(self.settings_tab)
        self.openCloseButton.setObjectName("openCloseButton")
        self.gridLayout_2.addWidget(self.openCloseButton, 10, 0, 1, 5)
        self.tabWidget.addTab(self.settings_tab, "")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.console_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sendButton = QtWidgets.QPushButton(self.console_tab)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 1, 4, 1, 1)
        self.timestampCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.timestampCheckBox.setChecked(False)
        self.timestampCheckBox.setObjectName("timestampCheckBox")
        self.gridLayout_3.addWidget(self.timestampCheckBox, 2, 0, 1, 1)
        self.crCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.crCheckBox.setChecked(True)
        self.crCheckBox.setObjectName("crCheckBox")
        self.gridLayout_3.addWidget(self.crCheckBox, 2, 1, 1, 1)
        self.lfCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.lfCheckBox.setChecked(True)
        self.lfCheckBox.setObjectName("lfCheckBox")
        self.gridLayout_3.addWidget(self.lfCheckBox, 2, 2, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.console_tab)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_3.addWidget(self.clearButton, 2, 4, 1, 1)
        self.consoleTextEdit = QtWidgets.QTextEdit(self.console_tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.consoleTextEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consoleTextEdit.setFont(font)
        self.consoleTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.consoleTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.gridLayout_3.addWidget(self.consoleTextEdit, 0, 0, 1, 5)
        self.crc16CheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.crc16CheckBox.setChecked(True)
        self.crc16CheckBox.setObjectName("crc16CheckBox")
        self.gridLayout_3.addWidget(self.crc16CheckBox, 2, 3, 1, 1)
        self.textToSend = QtWidgets.QLineEdit(self.console_tab)
        self.textToSend.setMinimumSize(QtCore.QSize(0, 0))
        self.textToSend.setObjectName("textToSend")
        self.gridLayout_3.addWidget(self.textToSend, 1, 0, 1, 4)
        self.tabWidget.addTab(self.console_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.STOPSIGNALING_Button = QtWidgets.QPushButton(self.tab)
        self.STOPSIGNALING_Button.setObjectName("STOPSIGNALING_Button")
        self.gridLayout_4.addWidget(self.STOPSIGNALING_Button, 0, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 2, 1, 2)
        self.LTAON_Button = QtWidgets.QPushButton(self.tab)
        self.LTAON_Button.setObjectName("LTAON_Button")
        self.gridLayout_4.addWidget(self.LTAON_Button, 0, 4, 1, 1)
        self.LTAOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTAOFF_Button.setObjectName("LTAOFF_Button")
        self.gridLayout_4.addWidget(self.LTAOFF_Button, 0, 5, 1, 1)
        self.SHTAON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTAON_Button.setObjectName("SHTAON_Button")
        self.gridLayout_4.addWidget(self.SHTAON_Button, 0, 6, 1, 1)
        self.SHTAOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTAOFF_Button.setObjectName("SHTAOFF_Button")
        self.gridLayout_4.addWidget(self.SHTAOFF_Button, 0, 7, 1, 1)
        self.OUTAON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTAON_Button.setObjectName("OUTAON_Button")
        self.gridLayout_4.addWidget(self.OUTAON_Button, 0, 8, 1, 1)
        self.OUTAOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTAOFF_Button.setObjectName("OUTAOFF_Button")
        self.gridLayout_4.addWidget(self.OUTAOFF_Button, 0, 9, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 10, 1, 1)
        self.SENDAPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDAPOWER_Button.setObjectName("SENDAPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDAPOWER_Button, 0, 11, 1, 1)
        self.APOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.APOWER_Text.sizePolicy().hasHeightForWidth())
        self.APOWER_Text.setSizePolicy(sizePolicy)
        self.APOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.APOWER_Text.setObjectName("APOWER_Text")
        self.gridLayout_4.addWidget(self.APOWER_Text, 0, 12, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 13, 1, 1)
        self.HEATERPOWER1_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER1_Button.setObjectName("HEATERPOWER1_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER1_Button, 0, 14, 1, 1)
        self.HEATERPOWER1_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER1_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER1_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER1_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER1_Text.setObjectName("HEATERPOWER1_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER1_Text, 0, 15, 1, 1)
        self.STARTSIGNALING_Button = QtWidgets.QPushButton(self.tab)
        self.STARTSIGNALING_Button.setObjectName("STARTSIGNALING_Button")
        self.gridLayout_4.addWidget(self.STARTSIGNALING_Button, 1, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 1, 2, 1, 2)
        self.LTBON_Button = QtWidgets.QPushButton(self.tab)
        self.LTBON_Button.setObjectName("LTBON_Button")
        self.gridLayout_4.addWidget(self.LTBON_Button, 1, 4, 1, 1)
        self.LTBOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTBOFF_Button.setObjectName("LTBOFF_Button")
        self.gridLayout_4.addWidget(self.LTBOFF_Button, 1, 5, 1, 1)
        self.SHTBON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTBON_Button.setObjectName("SHTBON_Button")
        self.gridLayout_4.addWidget(self.SHTBON_Button, 1, 6, 1, 1)
        self.SHTBOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTBOFF_Button.setObjectName("SHTBOFF_Button")
        self.gridLayout_4.addWidget(self.SHTBOFF_Button, 1, 7, 1, 1)
        self.OUTBON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTBON_Button.setObjectName("OUTBON_Button")
        self.gridLayout_4.addWidget(self.OUTBON_Button, 1, 8, 1, 1)
        self.OUTBOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTBOFF_Button.setObjectName("OUTBOFF_Button")
        self.gridLayout_4.addWidget(self.OUTBOFF_Button, 1, 9, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 10, 1, 1)
        self.SENDBPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDBPOWER_Button.setObjectName("SENDBPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDBPOWER_Button, 1, 11, 1, 1)
        self.BPOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BPOWER_Text.sizePolicy().hasHeightForWidth())
        self.BPOWER_Text.setSizePolicy(sizePolicy)
        self.BPOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.BPOWER_Text.setObjectName("BPOWER_Text")
        self.gridLayout_4.addWidget(self.BPOWER_Text, 1, 12, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 1, 13, 1, 1)
        self.HEATERPOWER2_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER2_Button.setObjectName("HEATERPOWER2_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER2_Button, 1, 14, 1, 1)
        self.HEATERPOWER2_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER2_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER2_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER2_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER2_Text.setObjectName("HEATERPOWER2_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER2_Text, 1, 15, 1, 1)
        self.FREQUENCY_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FREQUENCY_Text.sizePolicy().hasHeightForWidth())
        self.FREQUENCY_Text.setSizePolicy(sizePolicy)
        self.FREQUENCY_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.FREQUENCY_Text.setObjectName("FREQUENCY_Text")
        self.gridLayout_4.addWidget(self.FREQUENCY_Text, 2, 0, 1, 1)
        self.FREQUENCY_Button = QtWidgets.QPushButton(self.tab)
        self.FREQUENCY_Button.setObjectName("FREQUENCY_Button")
        self.gridLayout_4.addWidget(self.FREQUENCY_Button, 2, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 2, 3, 1, 1)
        self.LTCON_Button = QtWidgets.QPushButton(self.tab)
        self.LTCON_Button.setObjectName("LTCON_Button")
        self.gridLayout_4.addWidget(self.LTCON_Button, 2, 4, 1, 1)
        self.LTCOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTCOFF_Button.setObjectName("LTCOFF_Button")
        self.gridLayout_4.addWidget(self.LTCOFF_Button, 2, 5, 1, 1)
        self.SHTCON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTCON_Button.setObjectName("SHTCON_Button")
        self.gridLayout_4.addWidget(self.SHTCON_Button, 2, 6, 1, 1)
        self.SHTCOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTCOFF_Button.setObjectName("SHTCOFF_Button")
        self.gridLayout_4.addWidget(self.SHTCOFF_Button, 2, 7, 1, 1)
        self.OUTCON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTCON_Button.setObjectName("OUTCON_Button")
        self.gridLayout_4.addWidget(self.OUTCON_Button, 2, 8, 1, 1)
        self.OUTCOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTCOFF_Button.setObjectName("OUTCOFF_Button")
        self.gridLayout_4.addWidget(self.OUTCOFF_Button, 2, 9, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 2, 10, 1, 1)
        self.SENDCPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDCPOWER_Button.setObjectName("SENDCPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDCPOWER_Button, 2, 11, 1, 1)
        self.CPOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPOWER_Text.sizePolicy().hasHeightForWidth())
        self.CPOWER_Text.setSizePolicy(sizePolicy)
        self.CPOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.CPOWER_Text.setObjectName("CPOWER_Text")
        self.gridLayout_4.addWidget(self.CPOWER_Text, 2, 12, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 2, 13, 1, 1)
        self.HEATERPOWER3_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER3_Button.setObjectName("HEATERPOWER3_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER3_Button, 2, 14, 1, 1)
        self.HEATERPOWER3_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER3_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER3_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER3_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER3_Text.setObjectName("HEATERPOWER3_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER3_Text, 2, 15, 1, 1)
        self.DAC2A_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DAC2A_Text.sizePolicy().hasHeightForWidth())
        self.DAC2A_Text.setSizePolicy(sizePolicy)
        self.DAC2A_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.DAC2A_Text.setObjectName("DAC2A_Text")
        self.gridLayout_4.addWidget(self.DAC2A_Text, 3, 0, 1, 1)
        self.DAC2A_Button = QtWidgets.QPushButton(self.tab)
        self.DAC2A_Button.setObjectName("DAC2A_Button")
        self.gridLayout_4.addWidget(self.DAC2A_Button, 3, 1, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 3, 3, 1, 1)
        self.LTDON_Button = QtWidgets.QPushButton(self.tab)
        self.LTDON_Button.setObjectName("LTDON_Button")
        self.gridLayout_4.addWidget(self.LTDON_Button, 3, 4, 1, 1)
        self.LTDOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTDOFF_Button.setObjectName("LTDOFF_Button")
        self.gridLayout_4.addWidget(self.LTDOFF_Button, 3, 5, 1, 1)
        self.SHTDON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTDON_Button.setObjectName("SHTDON_Button")
        self.gridLayout_4.addWidget(self.SHTDON_Button, 3, 6, 1, 1)
        self.SHTDOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTDOFF_Button.setObjectName("SHTDOFF_Button")
        self.gridLayout_4.addWidget(self.SHTDOFF_Button, 3, 7, 1, 1)
        self.OUTDON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTDON_Button.setObjectName("OUTDON_Button")
        self.gridLayout_4.addWidget(self.OUTDON_Button, 3, 8, 1, 1)
        self.OUTDOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTDOFF_Button.setObjectName("OUTDOFF_Button")
        self.gridLayout_4.addWidget(self.OUTDOFF_Button, 3, 9, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem21, 3, 10, 1, 1)
        self.SENDDPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDDPOWER_Button.setObjectName("SENDDPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDDPOWER_Button, 3, 11, 1, 1)
        self.DPOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPOWER_Text.sizePolicy().hasHeightForWidth())
        self.DPOWER_Text.setSizePolicy(sizePolicy)
        self.DPOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.DPOWER_Text.setObjectName("DPOWER_Text")
        self.gridLayout_4.addWidget(self.DPOWER_Text, 3, 12, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem22, 3, 13, 1, 1)
        self.HEATERPOWER4_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER4_Button.setObjectName("HEATERPOWER4_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER4_Button, 3, 14, 1, 1)
        self.HEATERPOWER4_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER4_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER4_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER4_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER4_Text.setObjectName("HEATERPOWER4_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER4_Text, 3, 15, 1, 1)
        self.DAC2B_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DAC2B_Text.sizePolicy().hasHeightForWidth())
        self.DAC2B_Text.setSizePolicy(sizePolicy)
        self.DAC2B_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.DAC2B_Text.setObjectName("DAC2B_Text")
        self.gridLayout_4.addWidget(self.DAC2B_Text, 4, 0, 1, 1)
        self.DAC2B_Button = QtWidgets.QPushButton(self.tab)
        self.DAC2B_Button.setObjectName("DAC2B_Button")
        self.gridLayout_4.addWidget(self.DAC2B_Button, 4, 1, 1, 2)
        spacerItem23 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem23, 4, 3, 1, 1)
        self.LTEON_Button = QtWidgets.QPushButton(self.tab)
        self.LTEON_Button.setObjectName("LTEON_Button")
        self.gridLayout_4.addWidget(self.LTEON_Button, 4, 4, 1, 1)
        self.LTEOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTEOFF_Button.setObjectName("LTEOFF_Button")
        self.gridLayout_4.addWidget(self.LTEOFF_Button, 4, 5, 1, 1)
        self.SHTEON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTEON_Button.setObjectName("SHTEON_Button")
        self.gridLayout_4.addWidget(self.SHTEON_Button, 4, 6, 1, 1)
        self.SHTEOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTEOFF_Button.setObjectName("SHTEOFF_Button")
        self.gridLayout_4.addWidget(self.SHTEOFF_Button, 4, 7, 1, 1)
        self.OUTEON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTEON_Button.setObjectName("OUTEON_Button")
        self.gridLayout_4.addWidget(self.OUTEON_Button, 4, 8, 1, 1)
        self.OUTEOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTEOFF_Button.setObjectName("OUTEOFF_Button")
        self.gridLayout_4.addWidget(self.OUTEOFF_Button, 4, 9, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem24, 4, 10, 1, 1)
        self.SENDEPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDEPOWER_Button.setObjectName("SENDEPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDEPOWER_Button, 4, 11, 1, 1)
        self.EPOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EPOWER_Text.sizePolicy().hasHeightForWidth())
        self.EPOWER_Text.setSizePolicy(sizePolicy)
        self.EPOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.EPOWER_Text.setObjectName("EPOWER_Text")
        self.gridLayout_4.addWidget(self.EPOWER_Text, 4, 12, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem25, 4, 13, 1, 1)
        self.HEATERPOWER5_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER5_Button.setObjectName("HEATERPOWER5_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER5_Button, 4, 14, 1, 1)
        self.HEATERPOWER5_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER5_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER5_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER5_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER5_Text.setObjectName("HEATERPOWER5_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER5_Text, 4, 15, 1, 1)
        self.programsList = QtWidgets.QComboBox(self.tab)
        self.programsList.setObjectName("programsList")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.programsList.addItem("")
        self.gridLayout_4.addWidget(self.programsList, 5, 0, 1, 4)
        self.LTFON_Button = QtWidgets.QPushButton(self.tab)
        self.LTFON_Button.setObjectName("LTFON_Button")
        self.gridLayout_4.addWidget(self.LTFON_Button, 5, 4, 1, 1)
        self.LTFOFF_Button = QtWidgets.QPushButton(self.tab)
        self.LTFOFF_Button.setObjectName("LTFOFF_Button")
        self.gridLayout_4.addWidget(self.LTFOFF_Button, 5, 5, 1, 1)
        self.SHTFON_Button = QtWidgets.QPushButton(self.tab)
        self.SHTFON_Button.setObjectName("SHTFON_Button")
        self.gridLayout_4.addWidget(self.SHTFON_Button, 5, 6, 1, 1)
        self.SHTFOFF_Button = QtWidgets.QPushButton(self.tab)
        self.SHTFOFF_Button.setObjectName("SHTFOFF_Button")
        self.gridLayout_4.addWidget(self.SHTFOFF_Button, 5, 7, 1, 1)
        self.OUTFON_Button = QtWidgets.QPushButton(self.tab)
        self.OUTFON_Button.setObjectName("OUTFON_Button")
        self.gridLayout_4.addWidget(self.OUTFON_Button, 5, 8, 1, 1)
        self.OUTFOFF_Button = QtWidgets.QPushButton(self.tab)
        self.OUTFOFF_Button.setObjectName("OUTFOFF_Button")
        self.gridLayout_4.addWidget(self.OUTFOFF_Button, 5, 9, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem26, 5, 10, 1, 1)
        self.SENDFPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDFPOWER_Button.setObjectName("SENDFPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDFPOWER_Button, 5, 11, 1, 1)
        self.FPOWER_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPOWER_Text.sizePolicy().hasHeightForWidth())
        self.FPOWER_Text.setSizePolicy(sizePolicy)
        self.FPOWER_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.FPOWER_Text.setObjectName("FPOWER_Text")
        self.gridLayout_4.addWidget(self.FPOWER_Text, 5, 12, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 5, 13, 1, 1)
        self.HEATERPOWER6_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERPOWER6_Button.setObjectName("HEATERPOWER6_Button")
        self.gridLayout_4.addWidget(self.HEATERPOWER6_Button, 5, 14, 1, 1)
        self.HEATERPOWER6_Text = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HEATERPOWER6_Text.sizePolicy().hasHeightForWidth())
        self.HEATERPOWER6_Text.setSizePolicy(sizePolicy)
        self.HEATERPOWER6_Text.setMaximumSize(QtCore.QSize(35, 20))
        self.HEATERPOWER6_Text.setObjectName("HEATERPOWER6_Text")
        self.gridLayout_4.addWidget(self.HEATERPOWER6_Text, 5, 15, 1, 1)
        self.ALLLTON_Button = QtWidgets.QPushButton(self.tab)
        self.ALLLTON_Button.setObjectName("ALLLTON_Button")
        self.gridLayout_4.addWidget(self.ALLLTON_Button, 6, 4, 1, 1)
        self.ALLLTOFF_Button = QtWidgets.QPushButton(self.tab)
        self.ALLLTOFF_Button.setObjectName("ALLLTOFF_Button")
        self.gridLayout_4.addWidget(self.ALLLTOFF_Button, 6, 5, 1, 1)
        self.ALLSHTON_Button = QtWidgets.QPushButton(self.tab)
        self.ALLSHTON_Button.setObjectName("ALLSHTON_Button")
        self.gridLayout_4.addWidget(self.ALLSHTON_Button, 6, 6, 1, 1)
        self.ALLSHTOFF_Button = QtWidgets.QPushButton(self.tab)
        self.ALLSHTOFF_Button.setObjectName("ALLSHTOFF_Button")
        self.gridLayout_4.addWidget(self.ALLSHTOFF_Button, 6, 7, 1, 1)
        self.ALLOUTON_Button = QtWidgets.QPushButton(self.tab)
        self.ALLOUTON_Button.setObjectName("ALLOUTON_Button")
        self.gridLayout_4.addWidget(self.ALLOUTON_Button, 6, 8, 1, 1)
        self.ALLOUTOFF_Button = QtWidgets.QPushButton(self.tab)
        self.ALLOUTOFF_Button.setObjectName("ALLOUTOFF_Button")
        self.gridLayout_4.addWidget(self.ALLOUTOFF_Button, 6, 9, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem28, 6, 10, 1, 1)
        self.SENDALLPOWER_Button = QtWidgets.QPushButton(self.tab)
        self.SENDALLPOWER_Button.setObjectName("SENDALLPOWER_Button")
        self.gridLayout_4.addWidget(self.SENDALLPOWER_Button, 6, 11, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 6, 13, 1, 1)
        self.HEATERENABLE_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERENABLE_Button.setObjectName("HEATERENABLE_Button")
        self.gridLayout_4.addWidget(self.HEATERENABLE_Button, 6, 14, 1, 1)
        self.HEATERDISABLE_Button = QtWidgets.QPushButton(self.tab)
        self.HEATERDISABLE_Button.setObjectName("HEATERDISABLE_Button")
        self.gridLayout_4.addWidget(self.HEATERDISABLE_Button, 6, 15, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.baudrateList.setCurrentIndex(10)
        self.programsList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Skeyndor"))
        self.currentPortLabel.setText(_translate("Dialog", "No port selected"))
        self.currentConfigLabel.setText(_translate("Dialog", "Config: 8N1 115200"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.label_6.setText(_translate("Dialog", "Data width"))
        self.refreshPortsButton.setText(_translate("Dialog", "Refresh ports"))
        self.dataWidthList.setItemText(0, _translate("Dialog", "8 bits"))
        self.dataWidthList.setItemText(1, _translate("Dialog", "7 bits"))
        self.dataWidthList.setItemText(2, _translate("Dialog", "6 bits"))
        self.dataWidthList.setItemText(3, _translate("Dialog", "5 bits"))
        self.label.setText(_translate("Dialog", "Parity"))
        self.parityList.setItemText(0, _translate("Dialog", "None"))
        self.parityList.setItemText(1, _translate("Dialog", "Even"))
        self.parityList.setItemText(2, _translate("Dialog", "Odd"))
        self.parityList.setItemText(3, _translate("Dialog", "Mark"))
        self.parityList.setItemText(4, _translate("Dialog", "Space"))
        self.label_2.setText(_translate("Dialog", "Stop bits"))
        self.stopBitsList.setItemText(0, _translate("Dialog", "1 bit"))
        self.stopBitsList.setItemText(1, _translate("Dialog", "1.5 bits"))
        self.stopBitsList.setItemText(2, _translate("Dialog", "2 bits"))
        self.label_4.setText(_translate("Dialog", "Baudrate"))
        self.baudrateList.setItemText(0, _translate("Dialog", "300"))
        self.baudrateList.setItemText(1, _translate("Dialog", "600"))
        self.baudrateList.setItemText(2, _translate("Dialog", "900"))
        self.baudrateList.setItemText(3, _translate("Dialog", "1800"))
        self.baudrateList.setItemText(4, _translate("Dialog", "2400"))
        self.baudrateList.setItemText(5, _translate("Dialog", "4800"))
        self.baudrateList.setItemText(6, _translate("Dialog", "9600"))
        self.baudrateList.setItemText(7, _translate("Dialog", "19200"))
        self.baudrateList.setItemText(8, _translate("Dialog", "38400"))
        self.baudrateList.setItemText(9, _translate("Dialog", "57600"))
        self.baudrateList.setItemText(10, _translate("Dialog", "115200"))
        self.baudrateList.setItemText(11, _translate("Dialog", "125000"))
        self.baudrateList.setItemText(12, _translate("Dialog", "230400"))
        self.baudrateList.setItemText(13, _translate("Dialog", "460800"))
        self.baudrateList.setItemText(14, _translate("Dialog", "921600"))
        self.label_5.setText(_translate("Dialog", "Flow control"))
        self.flowControlList.setItemText(0, _translate("Dialog", "None"))
        self.flowControlList.setItemText(1, _translate("Dialog", "Xon/Xoff"))
        self.flowControlList.setItemText(2, _translate("Dialog", "RTS/CTS"))
        self.flowControlList.setItemText(3, _translate("Dialog", "DSR/DTR"))
        self.openCloseButton.setText(_translate("Dialog", "Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("Dialog", "Settings"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.timestampCheckBox.setText(_translate("Dialog", "Timestamp"))
        self.crCheckBox.setText(_translate("Dialog", "CR"))
        self.lfCheckBox.setText(_translate("Dialog", "LF"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.consoleTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">The serial communications will appear here when they start existing.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Lines you send will be marked in </span><span style=\" color:#ff0000;\">red</span><span style=\" color:#00ff00;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Lines you receive will be marked in green.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#00ff00;\"><br /></p></body></html>"))
        self.crc16CheckBox.setText(_translate("Dialog", "CRC16"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), _translate("Dialog", "Console"))
        self.STOPSIGNALING_Button.setText(_translate("Dialog", "Stop Signaling"))
        self.LTAON_Button.setText(_translate("Dialog", "LTA On"))
        self.LTAOFF_Button.setText(_translate("Dialog", "LTA Off"))
        self.SHTAON_Button.setText(_translate("Dialog", "SHTA On"))
        self.SHTAOFF_Button.setText(_translate("Dialog", "SHTA Off"))
        self.OUTAON_Button.setText(_translate("Dialog", "OUT A On"))
        self.OUTAOFF_Button.setText(_translate("Dialog", "OUT A Off"))
        self.SENDAPOWER_Button.setText(_translate("Dialog", "Send A Power"))
        self.APOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER1_Button.setText(_translate("Dialog", "Heater 1"))
        self.HEATERPOWER1_Text.setText(_translate("Dialog", "0"))
        self.STARTSIGNALING_Button.setText(_translate("Dialog", "Start Signaling"))
        self.LTBON_Button.setText(_translate("Dialog", "LTB On"))
        self.LTBOFF_Button.setText(_translate("Dialog", "LTB Off"))
        self.SHTBON_Button.setText(_translate("Dialog", "SHTB On"))
        self.SHTBOFF_Button.setText(_translate("Dialog", "SHTB Off"))
        self.OUTBON_Button.setText(_translate("Dialog", "OUT B On"))
        self.OUTBOFF_Button.setText(_translate("Dialog", "OUT B Off"))
        self.SENDBPOWER_Button.setText(_translate("Dialog", "Send B Power"))
        self.BPOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER2_Button.setText(_translate("Dialog", "Heater 2"))
        self.HEATERPOWER2_Text.setText(_translate("Dialog", "0"))
        self.FREQUENCY_Text.setText(_translate("Dialog", "28"))
        self.FREQUENCY_Button.setText(_translate("Dialog", "Frequency"))
        self.LTCON_Button.setText(_translate("Dialog", "LTC On"))
        self.LTCOFF_Button.setText(_translate("Dialog", "LTC Off"))
        self.SHTCON_Button.setText(_translate("Dialog", "SHTC On"))
        self.SHTCOFF_Button.setText(_translate("Dialog", "SHTC Off"))
        self.OUTCON_Button.setText(_translate("Dialog", "OUT C On"))
        self.OUTCOFF_Button.setText(_translate("Dialog", "OUT C Off"))
        self.SENDCPOWER_Button.setText(_translate("Dialog", "Send C Power"))
        self.CPOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER3_Button.setText(_translate("Dialog", "Heater 3"))
        self.HEATERPOWER3_Text.setText(_translate("Dialog", "0"))
        self.DAC2A_Text.setText(_translate("Dialog", "384"))
        self.DAC2A_Button.setText(_translate("Dialog", "DAC 2 A"))
        self.LTDON_Button.setText(_translate("Dialog", "LTD On"))
        self.LTDOFF_Button.setText(_translate("Dialog", "LTD Off"))
        self.SHTDON_Button.setText(_translate("Dialog", "SHTD On"))
        self.SHTDOFF_Button.setText(_translate("Dialog", "SHTD Off"))
        self.OUTDON_Button.setText(_translate("Dialog", "OUT D On"))
        self.OUTDOFF_Button.setText(_translate("Dialog", "OUT D Off"))
        self.SENDDPOWER_Button.setText(_translate("Dialog", "Send D Power"))
        self.DPOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER4_Button.setText(_translate("Dialog", "Heater 4"))
        self.HEATERPOWER4_Text.setText(_translate("Dialog", "0"))
        self.DAC2B_Text.setText(_translate("Dialog", "384"))
        self.DAC2B_Button.setText(_translate("Dialog", "DAC 2 B"))
        self.LTEON_Button.setText(_translate("Dialog", "LTE On"))
        self.LTEOFF_Button.setText(_translate("Dialog", "LTE Off"))
        self.SHTEON_Button.setText(_translate("Dialog", "SHTE On"))
        self.SHTEOFF_Button.setText(_translate("Dialog", "SHTE Off"))
        self.OUTEON_Button.setText(_translate("Dialog", "OUT E On"))
        self.OUTEOFF_Button.setText(_translate("Dialog", "OUT E Off"))
        self.SENDEPOWER_Button.setText(_translate("Dialog", "Send E Power"))
        self.EPOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER5_Button.setText(_translate("Dialog", "Heater 5"))
        self.HEATERPOWER5_Text.setText(_translate("Dialog", "0"))
        self.programsList.setItemText(0, _translate("Dialog", "Programa 0: Sinusoidal continua"))
        self.programsList.setItemText(1, _translate("Dialog", "Programa 1: Remodelante"))
        self.programsList.setItemText(2, _translate("Dialog", "Programa 2: Lipolítica Pepi"))
        self.programsList.setItemText(3, _translate("Dialog", "Programa 3: EMS - Edemas"))
        self.programsList.setItemText(4, _translate("Dialog", "Programa 4: Drenante - D2"))
        self.programsList.setItemText(5, _translate("Dialog", "Programa 5: Circulatoria - C2"))
        self.programsList.setItemText(6, _translate("Dialog", "Programa 6: Tensora contractora"))
        self.programsList.setItemText(7, _translate("Dialog", "Programa 7: TENS Endorfínico"))
        self.programsList.setItemText(8, _translate("Dialog", "Programa 8: TENS Convencional"))
        self.programsList.setItemText(9, _translate("Dialog", "Programa 9: TENS"))
        self.programsList.setItemText(10, _translate("Dialog", "Programa 10: EMS - Fuerza máxima"))
        self.programsList.setItemText(11, _translate("Dialog", "Programa 11: EMS - Fuerza máxima"))
        self.programsList.setItemText(12, _translate("Dialog", "Programa 12: EMS - Reafirmante"))
        self.programsList.setItemText(13, _translate("Dialog", "Programa 13: EMS - Reafirmante"))
        self.programsList.setItemText(14, _translate("Dialog", "Programa 14: Kotz - Barrido fibras lentas"))
        self.programsList.setItemText(15, _translate("Dialog", "Programa 15: Kotz - Barrido fibras rápidas"))
        self.programsList.setItemText(16, _translate("Dialog", "Programa 16: Isométrica"))
        self.LTFON_Button.setText(_translate("Dialog", "LTF On"))
        self.LTFOFF_Button.setText(_translate("Dialog", "LTF Off"))
        self.SHTFON_Button.setText(_translate("Dialog", "SHTF On"))
        self.SHTFOFF_Button.setText(_translate("Dialog", "SHTF Off"))
        self.OUTFON_Button.setText(_translate("Dialog", "OUT F On"))
        self.OUTFOFF_Button.setText(_translate("Dialog", "OUT F Off"))
        self.SENDFPOWER_Button.setText(_translate("Dialog", "Send F Power"))
        self.FPOWER_Text.setText(_translate("Dialog", "0"))
        self.HEATERPOWER6_Button.setText(_translate("Dialog", "Heater 6"))
        self.HEATERPOWER6_Text.setText(_translate("Dialog", "0"))
        self.ALLLTON_Button.setText(_translate("Dialog", "All LT On"))
        self.ALLLTOFF_Button.setText(_translate("Dialog", "All LT Off"))
        self.ALLSHTON_Button.setText(_translate("Dialog", "All SHT On"))
        self.ALLSHTOFF_Button.setText(_translate("Dialog", "All SHT Off"))
        self.ALLOUTON_Button.setText(_translate("Dialog", "All OUT On"))
        self.ALLOUTOFF_Button.setText(_translate("Dialog", "All OUT Off"))
        self.SENDALLPOWER_Button.setText(_translate("Dialog", "Send All"))
        self.HEATERENABLE_Button.setText(_translate("Dialog", "Enable Heaters"))
        self.HEATERDISABLE_Button.setText(_translate("Dialog", "Disable Heaters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Skeyndor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

