# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1067, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.currentConfigLabel = QtWidgets.QLabel(Dialog)
        self.currentConfigLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentConfigLabel.setObjectName("currentConfigLabel")
        self.gridLayout_4.addWidget(self.currentConfigLabel, 4, 0, 1, 1)
        self.infoLabel = QtWidgets.QLabel(Dialog)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout_4.addWidget(self.infoLabel, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 4, 1, 1, 1)
        self.currentPortLabel = QtWidgets.QLabel(Dialog)
        self.currentPortLabel.setObjectName("currentPortLabel")
        self.gridLayout_4.addWidget(self.currentPortLabel, 4, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.settings_tab)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.portsList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portsList.sizePolicy().hasHeightForWidth())
        self.portsList.setSizePolicy(sizePolicy)
        self.portsList.setMinimumSize(QtCore.QSize(70, 0))
        self.portsList.setCurrentText("")
        self.portsList.setMinimumContentsLength(1)
        self.portsList.setObjectName("portsList")
        self.portsList.addItem("")
        self.portsList.setItemText(0, "")
        self.gridLayout_2.addWidget(self.portsList, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settings_tab)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 2)
        self.refreshPortsButton = QtWidgets.QPushButton(self.settings_tab)
        self.refreshPortsButton.setObjectName("refreshPortsButton")
        self.gridLayout_2.addWidget(self.refreshPortsButton, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.dataWidthList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataWidthList.sizePolicy().hasHeightForWidth())
        self.dataWidthList.setSizePolicy(sizePolicy)
        self.dataWidthList.setMinimumSize(QtCore.QSize(70, 0))
        self.dataWidthList.setObjectName("dataWidthList")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.dataWidthList.addItem("")
        self.gridLayout_2.addWidget(self.dataWidthList, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settings_tab)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 2, 1, 1)
        self.parityList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parityList.sizePolicy().hasHeightForWidth())
        self.parityList.setSizePolicy(sizePolicy)
        self.parityList.setMinimumSize(QtCore.QSize(70, 0))
        self.parityList.setObjectName("parityList")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.parityList.addItem("")
        self.gridLayout_2.addWidget(self.parityList, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 4, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings_tab)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 2, 1, 1)
        self.stopBitsList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBitsList.sizePolicy().hasHeightForWidth())
        self.stopBitsList.setSizePolicy(sizePolicy)
        self.stopBitsList.setMinimumSize(QtCore.QSize(70, 0))
        self.stopBitsList.setObjectName("stopBitsList")
        self.stopBitsList.addItem("")
        self.stopBitsList.addItem("")
        self.stopBitsList.addItem("")
        self.gridLayout_2.addWidget(self.stopBitsList, 5, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 5, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.settings_tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 2, 1, 1)
        self.baudrateList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrateList.sizePolicy().hasHeightForWidth())
        self.baudrateList.setSizePolicy(sizePolicy)
        self.baudrateList.setMinimumSize(QtCore.QSize(70, 0))
        self.baudrateList.setObjectName("baudrateList")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.baudrateList.addItem("")
        self.gridLayout_2.addWidget(self.baudrateList, 6, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 6, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settings_tab)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 2, 1, 1)
        self.flowControlList = QtWidgets.QComboBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowControlList.sizePolicy().hasHeightForWidth())
        self.flowControlList.setSizePolicy(sizePolicy)
        self.flowControlList.setMinimumSize(QtCore.QSize(70, 0))
        self.flowControlList.setObjectName("flowControlList")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.flowControlList.addItem("")
        self.gridLayout_2.addWidget(self.flowControlList, 9, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 9, 4, 1, 1)
        self.openCloseButton = QtWidgets.QPushButton(self.settings_tab)
        self.openCloseButton.setObjectName("openCloseButton")
        self.gridLayout_2.addWidget(self.openCloseButton, 10, 0, 1, 5)
        self.tabWidget.addTab(self.settings_tab, "")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.console_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sendButton = QtWidgets.QPushButton(self.console_tab)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 1, 4, 1, 1)
        self.timestampCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.timestampCheckBox.setChecked(False)
        self.timestampCheckBox.setObjectName("timestampCheckBox")
        self.gridLayout_3.addWidget(self.timestampCheckBox, 2, 0, 1, 1)
        self.crCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.crCheckBox.setChecked(True)
        self.crCheckBox.setObjectName("crCheckBox")
        self.gridLayout_3.addWidget(self.crCheckBox, 2, 1, 1, 1)
        self.lfCheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.lfCheckBox.setChecked(True)
        self.lfCheckBox.setObjectName("lfCheckBox")
        self.gridLayout_3.addWidget(self.lfCheckBox, 2, 2, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.console_tab)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_3.addWidget(self.clearButton, 2, 4, 1, 1)
        self.consoleTextEdit = QtWidgets.QTextEdit(self.console_tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.consoleTextEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consoleTextEdit.setFont(font)
        self.consoleTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.consoleTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.gridLayout_3.addWidget(self.consoleTextEdit, 0, 0, 1, 5)
        self.crc16CheckBox = QtWidgets.QCheckBox(self.console_tab)
        self.crc16CheckBox.setChecked(True)
        self.crc16CheckBox.setObjectName("crc16CheckBox")
        self.gridLayout_3.addWidget(self.crc16CheckBox, 2, 3, 1, 1)
        self.textToSend = QtWidgets.QLineEdit(self.console_tab)
        self.textToSend.setMinimumSize(QtCore.QSize(0, 0))
        self.textToSend.setObjectName("textToSend")
        self.gridLayout_3.addWidget(self.textToSend, 1, 0, 1, 4)
        self.tabWidget.addTab(self.console_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(758, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 3, 3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.baudrateList.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Skeyndor"))
        self.currentConfigLabel.setText(_translate("Dialog", "Config: 8N1 115200"))
        self.currentPortLabel.setText(_translate("Dialog", "No port selected"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.label_6.setText(_translate("Dialog", "Data width"))
        self.refreshPortsButton.setText(_translate("Dialog", "Refresh ports"))
        self.dataWidthList.setItemText(0, _translate("Dialog", "8 bits"))
        self.dataWidthList.setItemText(1, _translate("Dialog", "7 bits"))
        self.dataWidthList.setItemText(2, _translate("Dialog", "6 bits"))
        self.dataWidthList.setItemText(3, _translate("Dialog", "5 bits"))
        self.label.setText(_translate("Dialog", "Parity"))
        self.parityList.setItemText(0, _translate("Dialog", "None"))
        self.parityList.setItemText(1, _translate("Dialog", "Even"))
        self.parityList.setItemText(2, _translate("Dialog", "Odd"))
        self.parityList.setItemText(3, _translate("Dialog", "Mark"))
        self.parityList.setItemText(4, _translate("Dialog", "Space"))
        self.label_2.setText(_translate("Dialog", "Stop bits"))
        self.stopBitsList.setItemText(0, _translate("Dialog", "1 bit"))
        self.stopBitsList.setItemText(1, _translate("Dialog", "1.5 bits"))
        self.stopBitsList.setItemText(2, _translate("Dialog", "2 bits"))
        self.label_4.setText(_translate("Dialog", "Baudrate"))
        self.baudrateList.setItemText(0, _translate("Dialog", "300"))
        self.baudrateList.setItemText(1, _translate("Dialog", "600"))
        self.baudrateList.setItemText(2, _translate("Dialog", "900"))
        self.baudrateList.setItemText(3, _translate("Dialog", "1800"))
        self.baudrateList.setItemText(4, _translate("Dialog", "2400"))
        self.baudrateList.setItemText(5, _translate("Dialog", "4800"))
        self.baudrateList.setItemText(6, _translate("Dialog", "9600"))
        self.baudrateList.setItemText(7, _translate("Dialog", "19200"))
        self.baudrateList.setItemText(8, _translate("Dialog", "38400"))
        self.baudrateList.setItemText(9, _translate("Dialog", "57600"))
        self.baudrateList.setItemText(10, _translate("Dialog", "115200"))
        self.baudrateList.setItemText(11, _translate("Dialog", "125000"))
        self.baudrateList.setItemText(12, _translate("Dialog", "230400"))
        self.baudrateList.setItemText(13, _translate("Dialog", "460800"))
        self.baudrateList.setItemText(14, _translate("Dialog", "921600"))
        self.label_5.setText(_translate("Dialog", "Flow control"))
        self.flowControlList.setItemText(0, _translate("Dialog", "None"))
        self.flowControlList.setItemText(1, _translate("Dialog", "Xon/Xoff"))
        self.flowControlList.setItemText(2, _translate("Dialog", "RTS/CTS"))
        self.flowControlList.setItemText(3, _translate("Dialog", "DSR/DTR"))
        self.openCloseButton.setText(_translate("Dialog", "Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("Dialog", "Settings"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.timestampCheckBox.setText(_translate("Dialog", "Timestamp"))
        self.crCheckBox.setText(_translate("Dialog", "CR"))
        self.lfCheckBox.setText(_translate("Dialog", "LF"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.consoleTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">The serial communications will appear here when they start existing.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Lines you send will be marked in </span><span style=\" color:#ff0000;\">red</span><span style=\" color:#00ff00;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Lines you receive will be marked in green.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#00ff00;\"><br /></p></body></html>"))
        self.crc16CheckBox.setText(_translate("Dialog", "CRC16"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), _translate("Dialog", "Console"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "Files should be listed here"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Dialog", "Start update"))
        self.pushButton_2.setText(_translate("Dialog", "Stop update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Skeyndor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

